services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik.toml:/etc/traefik/traefik.toml"
      - "letsencrypt:/letsencrypt"

  tweebuilder:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_ALGORITHM=${AUTH_ALGORITHM}
      - GDRIVE_CHANNEL_TOKEN=${GDRIVE_CHANNEL_TOKEN}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./cache:/app/cache
      - ./build:/app/build
    depends_on:
      - postgres
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.tylergarman.net`)"
      - "traefik.http.routers.fastapi.entrypoints=websecure"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"

  postgres:
    image: postgres:18-alpine
    shm_size: 128MB
    command: postgres -c shared_buffers=128MB -c autovacuum=on -c max_connections=50
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./src/tweebuilder/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1GB
    restart: unless-stopped

volumes:
  postgres-data:
  letsencrypt:
