services:
  tweebuilder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
      - ./build:/app/build
      - ./tweego:/app/tweego
    restart: unless-stopped
